---
- name: Schema Registry Role Bindings
  hosts: schema_registry
  gather_facts: false
  environment: "{{ proxy_env }}"
  tasks:
    - name: Schema Registry Role Bindings
      import_role:
        name: confluent.schema_registry
        tasks_from: rbac.yml
      vars:
        cluster_id_source: zookeeper
        copy_certs: false
      run_once: true
      when: rbac_enabled|bool

- name: Schema Registry Upgrade
  hosts: schema_registry
  environment: "{{ proxy_env }}"
  serial: 1
  # there is a schema registry leader, should think about the master/follower thing
  # look in schema reg docs
  tasks:
    - import_role:
        name: confluent.variables

    - shell: "egrep 'ssl.client.auth ?= ?true' {{ schema_registry.config_file }}"
      register: mtls_check
      failed_when: false

    - name: Set MTLS Variable
      set_fact:
        schema_registry_ssl_mutual_auth_enabled: "{{ true if mtls_check.rc == 0 else false}}"

    - name: Get Package Facts
      package_facts:
        manager: auto

    - set_fact:
        confluent_server_enabled: true
      when: ansible_facts.packages['confluent-server'] is defined

    - set_fact:
        confluent_server_enabled: false
      when: ansible_facts.packages['confluent-kafka-2.12'] is defined

    - name: Set Current Package Version
      set_fact:
        schema_registry_current_version: "{{ ansible_facts.packages['confluent-schema-registry'][0]['version'] }}"

    - debug:
        msg: "Current version: {{schema_registry_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Schema Registry
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ schema_registry_service_name }}"
        packages: "{{ schema_registry_packages }}"
        backup_files:
          - "{{ schema_registry.config_file }}"
          - "{{ schema_registry.systemd_override }}"
        restore_files:
          - "{{ schema_registry.config_file }}"
      when:
        - schema_registry_current_version != confluent_full_package_version
        - schema_registry_current_version != confluent_package_version

    - name: Schema Registry Health Check
      import_role:
        name: confluent.schema_registry
        tasks_from: health_check.yml
      when: not ansible_check_mode
