---
- name: Control Center Upgrade
  hosts: control_center
  environment: "{{ proxy_env }}"
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables

    - name: Get Package Facts
      package_facts:
        manager: auto

    - set_fact:
        confluent_server_enabled: true
      when: ansible_facts.packages['confluent-server'] is defined

    - set_fact:
        confluent_server_enabled: false
      when: ansible_facts.packages['confluent-kafka-2.12'] is defined

    - name: Set Current Package Version
      set_fact:
        control_center_current_version: "{{ ansible_facts.packages['confluent-control-center'][0]['version'] }}"

    - debug:
        msg: "Current version: {{control_center_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Control Center
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ control_center_service_name }}"
        packages: "{{ control_center_packages }}"
        backup_files:
          - "{{ control_center.config_file }}"
          - "{{ control_center.systemd_override }}"
        restore_files:
          - "{{ control_center.config_file }}"
      when:
        - control_center_current_version != confluent_full_package_version
        - control_center_current_version != confluent_package_version

    - name: Control Center Health Check
      import_role:
        name: confluent.control_center
        tasks_from: health_check.yml
      when: not ansible_check_mode
