---
- name: Kafka Rest Role Bindings
  hosts: kafka_rest
  gather_facts: false
  environment: "{{ proxy_env }}"
  tasks:
    - name: Kafka Rest Role Bindings
      import_role:
        name: confluent.kafka_rest
        tasks_from: rbac.yml
      vars:
        cluster_id_source: zookeeper
        copy_certs: false
      run_once: true
      when: rbac_enabled|bool

- name: Kafka Rest Upgrade
  hosts: kafka_rest
  environment: "{{ proxy_env }}"
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables

    - shell: "egrep 'ssl.client.auth ?= ?true' {{ kafka_rest.config_file }}"
      register: mtls_check
      failed_when: false

    - name: Set MTLS Variable
      set_fact:
        kafka_rest_ssl_mutual_auth_enabled: "{{ true if mtls_check.rc == 0 else false}}"

    - name: Get Package Facts
      package_facts:
        manager: auto

    - set_fact:
        confluent_server_enabled: true
      when: ansible_facts.packages['confluent-server'] is defined

    - set_fact:
        confluent_server_enabled: false
      when: ansible_facts.packages['confluent-kafka-2.12'] is defined

    - name: Set Current Package Version
      set_fact:
        kafka_rest_current_version: "{{ ansible_facts.packages['confluent-kafka-rest'][0]['version'] }}"

    - debug:
        msg: "Current version: {{kafka_rest_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Kafka Connect
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ kafka_rest_service_name }}"
        packages: "{{ kafka_rest_packages }}"
        backup_files:
          - "{{ kafka_rest.config_file }}"
          - "{{ kafka_rest.systemd_override }}"
        restore_files:
          - "{{ kafka_rest.config_file }}"
      when:
        - kafka_rest_current_version != confluent_full_package_version
        - kafka_rest_current_version != confluent_package_version

    - name: Kafka Rest Health Check
      import_role:
        name: confluent.kafka_rest
        tasks_from: health_check.yml
      when: not ansible_check_mode
