---
- name: Kafka Broker Upgrade - Configure Rest API
  hosts: kafka_broker
  gather_facts: false
  serial: 1
  vars:
    kafka_broker_rest_proxy_enabled: true
    erp_properties:
      kafka.rest.enable: 'true'
  handlers:
    - name: restart kafka
      include_tasks: roles/confluent.kafka_broker/tasks/restart_kafka.yml
  tasks:
    - import_role:
        name: confluent.variables

    - name: Set confluent_server_enabled and kafka_broker_jolokia_ssl_enabled Variables
      include_tasks: tasks/set_kafka_broker_jolokia_ssl_enabled.yml

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy.enabled|bool
        - confluent_server_enabled|bool

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy_ssl.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy_ssl.enabled|bool
        - confluent_server_enabled|bool

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy_ssl_fips.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy_ssl_fips.enabled|bool
        - confluent_server_enabled|bool

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy_client_bootstrap.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy_client_bootstrap.enabled|bool
        - confluent_server_enabled|bool

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy_client.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy_client.enabled|bool
        - confluent_server_enabled|bool

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy_rbac.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy_rbac.enabled|bool
        - confluent_server_enabled|bool

    - set_fact:
        erp_properties: "{{ erp_properties | combine(kafka_broker_properties.embedded_rest_proxy_rbac_ssl.properties) }}"
      when:
        - kafka_broker_properties.embedded_rest_proxy_rbac_ssl.enabled|bool
        - confluent_server_enabled|bool

    - name: Add Kafka Rest Configuration
      lineinfile:
        name: "{{kafka_broker.config_file}}"
        line: "{{item.key}}={{item.value}}"
        regexp: "{{item.key}}=.*"
        state: present
      loop: "{{ erp_properties|dict2items }}"
      notify: restart kafka
      when: confluent_server_enabled|bool

    - name: Print Error Message
      debug:
        msg: "You must be using confluent-server not confluent-kafka for this feature"
      when: not confluent_server_enabled|bool
