---
- name: Kafka Broker - Prerequisites
  hosts: kafka_broker
  serial: 1
  vars:
    kafka_broker_upgrade_start_version: "5.3"
    kafka_broker_rest_proxy_enabled: false
  handlers:
    - name: restart kafka
      include_tasks: roles/confluent.kafka_broker/tasks/restart_kafka.yml
  tasks:
    - import_role:
        name: confluent.variables

    - name: Set confluent_server_enabled and kafka_broker_jolokia_ssl_enabled Variables
      include_tasks: tasks/set_kafka_broker_jolokia_ssl_enabled.yml

    - set_fact:
        inter_broker_protocol_version: 2.3
        log_message_format_version: 2.3
      when: kafka_broker_upgrade_start_version is match('5.3.*')

    - set_fact:
        inter_broker_protocol_version: 2.4
        log_message_format_version: 2.4
      when: kafka_broker_upgrade_start_version is match('5.4.*')

    - set_fact:
        inter_broker_protocol_version: 2.5
        log_message_format_version: 2.5
      when: kafka_broker_upgrade_start_version is match('5.5.*')

    - set_fact:
        inter_broker_protocol_version: 2.6
        log_message_format_version: 2.6
      when: kafka_broker_upgrade_start_version is match('6.0.*')

    - name: Set Inter-Broker Protocol Version to Current Version
      lineinfile:
        path: "{{kafka_broker.config_file}}"
        line: "inter.broker.protocol.version={{inter_broker_protocol_version}}"
        regexp: inter.broker.protocol.version.*
        state: present

    - name: Set Log Message Format Version to Current Version
      lineinfile:
        path: "{{kafka_broker.config_file}}"
        line: "log.message.format.version={{log_message_format_version}}"
        regexp: log.message.format.version.*
        state: present

    - name: Make sure Controlled Shutdown Property is not set to False
      lineinfile:
        path: "{{kafka_broker.config_file}}"
        # Default value for controlled.shutdown.enable is true
        # Removing the line and restarting the service will set property to true
        line: controlled.shutdown.enable=false
        state: absent
      notify: restart kafka

- name: Kafka Broker Upgrade - Host Ordering
  hosts: kafka_broker
  serial: 1
  tasks:
    # Sets active_controller_count var for each host
    - name: Create Ordered Kafka Broker Groups
      import_tasks: tasks/create_ordered_kafka_groups.yml
      vars:
        controller_group: controller
        non_controller_group: non_controllers

    - name: Set Current Package Version of confluent-server
      set_fact:
        kafka_broker_current_version: "{{ ansible_facts.packages['confluent-server'][0]['version'] }}"
      when: confluent_server_enabled|bool

    - name: Set Current Package Version of confluent-kafka-2.12
      set_fact:
        kafka_broker_current_version: "{{ ansible_facts.packages['confluent-kafka-2.12'][0]['version'] }}"
      when: not confluent_server_enabled|bool and not confluent_kafka_upgraded|bool

    - name: Set Current Package Version of confluent-kafka
      set_fact:
        kafka_broker_current_version: "{{ ansible_facts.packages['confluent-kafka'][0]['version'] }}"
      when: not confluent_server_enabled|bool and confluent_kafka_upgraded|bool

    - name: Set Current Package Version of confluent-security
      set_fact:
        confluent_security_current_version: "{{ ansible_facts.packages['confluent-security'][0]['version'] }}"

    # On colocated zk/kafka hosts, the kafka package will already be upgraded, need to check confluent-server as well
    - name: Set Current Package Version
      set_fact:
        kafka_broker_current_version: "{{ [kafka_broker_current_version, confluent_security_current_version] | min }}"

    - debug:
        msg: "Current version: {{kafka_broker_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Add host to Non Controller Group
      add_host:
        name: "{{ inventory_hostname }}"
        group: upgrade_non_controllers
      delegate_to: localhost
      changed_when: false
      when:
        - active_controller_count|int == 0
        - kafka_broker_current_version != confluent_full_package_version
        - kafka_broker_current_version != confluent_package_version

    - name: Add host to Controller Group
      add_host:
        name: "{{ inventory_hostname }}"
        group: upgrade_controller
      delegate_to: localhost
      changed_when: false
      when:
        - active_controller_count|int == 1
        - kafka_broker_current_version != confluent_full_package_version
        - kafka_broker_current_version != confluent_package_version

- name: Kafka Broker Upgrade
  # Putting controller group last here with serial=1 has the controller as the last host to run
  hosts: upgrade_non_controllers,upgrade_controller
  environment: "{{ proxy_env }}"
  serial: 1
  tags:
    - upgrade
  tasks:
    - import_role:
        name: confluent.variables

    - name: Create Backup Directory
      file:
        path: "/tmp/upgrade/{{ kafka_broker_service_name }}"
        state: directory
        mode: 0640

    - set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Backup Configuration files
      copy:
        src: "{{ item }}"
        remote_src: true
        dest: "/tmp/upgrade/{{ kafka_broker_service_name }}/{{ item | basename }}-{{timestamp}}"
      loop:
        - "{{ kafka_broker.config_file }}"
        - "{{ kafka_broker.systemd_override }}"
        - "{{ zookeeper.config_file }}"
      # Files cannot be copied because directory is not created in check mode
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Stop Service
      systemd:
        name: "{{ kafka_broker_service_name }}"
        state: stopped

    - name: Configure Repositories
      import_role:
        name: confluent.common
      vars:
        install_java: false

    - name: Remove Confluent-Kafka Packages - Red Hat
      yum:
        name: confluent-kafka-2.12
        state: absent
      when:
        - ansible_os_family == "RedHat"
        - not confluent_server_enabled|bool
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Remove Confluent-Kafka Packages - Debian
      apt:
        name: confluent-kafka-2.12
        state: absent
      when:
        - ansible_os_family == "Debian"
        - not confluent_server_enabled|bool
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install the Packages - Red Hat
      yum:
        name: "{{item}}{{confluent_package_redhat_suffix}}"
        state: latest
        update_cache: true
      loop: "{{ kafka_broker_packages }}"
      when: ansible_os_family == "RedHat"
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install the Packages - Debian
      apt:
        name: "{{item}}{{confluent_package_debian_suffix}}"
        update_cache: true
      loop: "{{ kafka_broker_packages }}"
      when: ansible_os_family == "Debian"
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Put back configuration
      copy:
        dest: "{{ item }}"
        remote_src: true
        src: "/tmp/upgrade/{{ kafka_broker_service_name }}/{{ item | basename }}-{{timestamp}}"
      loop:
        - "{{ kafka_broker.config_file }}"
        - "{{ zookeeper.config_file }}"
      # Files cannot be copied because directory is not created in check mode
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Disabling Embedded Rest Proxy
      # Existing server.properties is missing configuration
      lineinfile:
        path: "{{ kafka_broker.config_file }}"
        regexp: 'kafka.rest.enable=*'
        line: 'kafka.rest.enable=false'

    - name: Restart Service
      systemd:
        daemon_reload: true
        name: "{{ kafka_broker_service_name }}"
        state: restarted

    - name: Kafka Broker Health Check
      include_tasks: roles/confluent.kafka_broker/tasks/health_check.yml
      vars:
        kafka_broker_rest_proxy_enabled: false
      when: not ansible_check_mode

- name: Kafka Broker Upgrade - Set Inter-Broker Protocol to Current Version
  hosts: kafka_broker
  gather_facts: false
  serial: 1
  tags:
    - inter_broker_protocol_version
  vars:
    upgrade_to_version: "6.0"
    kafka_broker_rest_proxy_enabled: false
  handlers:
    - name: restart kafka
      include_tasks: roles/confluent.kafka_broker/tasks/restart_kafka.yml
  tasks:
    - import_role:
        name: confluent.variables

    - set_fact:
        inter_broker_protocol_version: 2.3
      when: upgrade_to_version is match('5.3.*')

    - set_fact:
        inter_broker_protocol_version: 2.4
      when: upgrade_to_version is match('5.4.*')

    - set_fact:
        inter_broker_protocol_version: 2.5
      when: upgrade_to_version is match('5.5.*')

    - set_fact:
        inter_broker_protocol_version: 2.6
      when: upgrade_to_version is match('6.0.*')

    - name: Set Inter-Broker Protocol Version to Current Version
      lineinfile:
        name: "{{kafka_broker.config_file}}"
        line: "inter.broker.protocol.version={{inter_broker_protocol_version}}"
        regexp: inter.broker.protocol.version.*
        state: present
      notify: restart kafka
